proyectoid: "myproyecto1" #nombre de la carpeta principal del proyecto
ecrRepositoryDEV: "MiRepositorio_dev_1" #nombre del repositorio en ECR para el ambiente DEV
ecrRepositoryUAT: "MiRepositorio_uat_1" #nombre del repositorio en ECR para el ambiente UAT
ecrRepositoryPRD: "MiRepositorio_prd_1" #nombre del repositorio en ECR para el ambiente PRD
LambdaDEV: "MiLambda_dev_1" #nombre de la función Lambda para el ambiente DEV
LambdaUAT: "MiLambda_uat_1" #nombre de la función Lambda para el ambiente UAT
LambdaPRD: "MiLambda_prd_1" #nombre de la función Lambda para el ambiente PRD

proyectoid: "myproyecto2"
ecrRepositoryDEV: "MiRepositorio_dev_2"
ecrRepositoryUAT: "MiRepositorio_uat_2"
ecrRepositoryPRD: "MiRepositorio_prd_2"
LambdaDEV: "MiLambda_dev_2"
LambdaUAT: "MiLambda_uat_2"
LambdaPRD: "MiLambda_prd_2"

proyectoid: "myproyecto3"
ecrRepositoryDEV: "MiRepositorio_dev_3"
ecrRepositoryUAT: "MiRepositorio_uat_3"
ecrRepositoryPRD: "MiRepositorio_prd_3"
LambdaDEV: "MiLambda_dev_3"
LambdaUAT: "MiLambda_uat_3"
LambdaPRD: "MiLambda_prd_3"