proyectos:
  - proyectoid: "person-connect" #nombre de la carpeta principal del proyecto
    dockerfilePath: "/ingesta/lambdas/person-connect/Dockerfile" #nombre del Dockerfile dentro de la carpeta del proyecto
    deploy: "lambda" #tipo de despliegue, puede ser "lambda" o "S3"
    ecrRepositoryDEV: "MiRepositorio_dev_1" #nombre del repositorio en ECR para el ambiente DEV
    ecrRepositoryUAT: "MiRepositorio_uat_1" #nombre del repositorio en ECR para el ambiente UAT
    ecrRepositoryPRD: "MiRepositorio_prd_1" #nombre del repositorio en ECR para el ambiente PRD
    LambdaDEV: "MiLambda_dev_1" #nombre de la función Lambda para el ambiente DEV
    LambdaUAT: "MiLambda_uat_1" #nombre de la función Lambda para el ambiente UAT
    LambdaPRD: "MiLambda_prd_1" #nombre de la función Lambda para el ambiente PRD

  - proyectoid: "person-login"
    dockerfilePath: "/ingesta/lambdas/person-login/Dockerfile"
    deploy: "lambda"
    ecrRepositoryDEV: "MiRepositorio_dev_2"
    ecrRepositoryUAT: "MiRepositorio_uat_2"
    ecrRepositoryPRD: "MiRepositorio_prd_2"
    LambdaDEV: "MiLambda_dev_2"
    LambdaUAT: "MiLambda_uat_2"
    LambdaPRD: "MiLambda_prd_2"

  - proyectoid: "person-process"
    dockerfilePath: "/transformacion/lambdas/person-process/Dockerfile"
    deploy: "lambda"
    ecrRepositoryDEV: "MiRepositorio_dev_3"
    ecrRepositoryUAT: "MiRepositorio_uat_3"
    ecrRepositoryPRD: "MiRepositorio_prd_3"
    LambdaDEV: "MiLambda_dev_3"
    LambdaUAT: "MiLambda_uat_3"
    LambdaPRD: "MiLambda_prd_3"

  - proyectoid: "castillo-connect"
    pythonfilePath: "/ingesta/glue/castillo-connect/src"
    deploy: "s3"
    S3path: "castillo-connect/"
    s3RepositoryDEV: "mi-bucket_dev_1"
    s3RepositoryUAT: "mi-bucket_uat_1"
    s3RepositoryPRD: "mi-bucket_prd_1"

  - proyectoid: "castillo-login"
    pythonfilePath: "/ingesta/glue/castillo-login/src"
    deploy: "s3"
    S3path: "castillo-login/"
    s3RepositoryDEV: "mi-bucket_dev_1"
    s3RepositoryUAT: "mi-bucket_uat_1"
    s3RepositoryPRD: "mi-bucket_prd_1"

  - proyectoid: "balcazar-process"
    pythonfilePath: "/transformacion/glue/balcazar-process/src"
    deploy: "s3"
    S3path: "balcazar-process/"
    s3RepositoryDEV: "mi-bucket_dev_1"
    s3RepositoryUAT: "mi-bucket_uat_1"
    s3RepositoryPRD: "mi-bucket_prd_1"

  - proyectoid: "ingesta-step-function1"
    stepFilePath: "/ingesta/stepfunction/ingesta-step-function1"
    deploy: "stepfunction"
    path: "ingesta-step-function1"
    definitionName: "ingesta-step-function1.json"
    stateMachineDEV: "MiStateMachine_dev_1"
    stateMachineUAT: "MiStateMachine_uat_1"
    stateMachinePRD: "MiStateMachine_prd_1"

  - proyectoid: "ingesta-step-function2"
    stepFilePath: "/ingesta/stepfunction/ingesta-step-function2"
    deploy: "stepfunction"
    path: "ingesta-step-function2"
    definitionName: "ingesta-step-function2.json"
    stateMachineDEV: "MiStateMachine_dev_2"
    stateMachineUAT: "MiStateMachine_uat_2"
    stateMachinePRD: "MiStateMachine_prd_2"

  - proyectoid: "transformacion-step-function"
    stepFilePath: "/transformacion/stepfunction/transformacion-step-function"
    deploy: "stepfunction"
    path: "transformacion-step-function"
    definitionName: "transformacion-step-function.json"
    stateMachineDEV: "MiStateMachine_dev_3"
    stateMachineUAT: "MiStateMachine_uat_3"
    stateMachinePRD: "MiStateMachine_prd_3"