sonar.host.url=https://sonarcloud.io
sonar.organization=interbank
sonar.projectKey=dso-pe.interbank:dso-angular-sample-web
sonar.sourceEncoding=UTF-8
sonar.sources=app/src
sonar.exclusions=**/node_modules/**
sonar.tests=app/src
sonar.test.inclusions=**/*.spec.ts
sonar.typescript.lcov.reportPaths=app/testresults/coverage/lcov.info
sonar.testExecutionReportPaths=app/testresults/sonar/sonar-report.xml