name: CI
run-name: "CI/CD - Build & Push to ECR 1.0.${{ github.run_number }}"

on:
  push:
    branches:
       - main
#       - develop
#   pull_request:
#     branches:
#       - main
  workflow_dispatch:
    inputs:
      ambiente:
        description: "Ambiente de despliegue"
        required: true
        default: "myproyecto1"
        type: choice
        options:
          - myproyecto1
          - myproyecto2
          - myproyecto3
env:
    TAGS: 1.0.${{ github.run_number }}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # Required for OIDC authentication

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: mis variables de entorno
      #   run: |
      #     CONFIG_FILE=".github/workflows/config.yml"
      #     proyects=("myproyecto1" "myproyecto2")
      #     for proy in "${proyects[@]}"; do
      #       echo "${proy}_ecrRepositoryDEV=$(yq ".$proy.ecrRepositoryDEV" $CONFIG_FILE)" >> $GITHUB_ENV
      #       echo "${proy}_ecrRepositoryUAT=$(yq ".$proy.ecrRepositoryUAT" $CONFIG_FILE)" >> $GITHUB_ENV
      #       echo "${proy}_ecrRepositoryPRD=$(yq ".$proy.ecrRepositoryPRD" $CONFIG_FILE)" >> $GITHUB_ENV
      #       echo "${proy}_LambdaDEV=$(yq ".$proy.LambdaDEV" $CONFIG_FILE)" >> $GITHUB_ENV
      #       echo "${proy}_LambdaUAT=$(yq ".$proy.LambdaUAT" $CONFIG_FILE)" >> $GITHUB_ENV
      #       echo "${proy}_LambdaPRD=$(yq ".$proy.LambdaPRD" $CONFIG_FILE)" >> $GITHUB_ENV
      #     done

      #     echo "---- Variables de entorno cargadas ----"
      #     env | grep -E "^(myproyecto1|myproyecto2)_"


      - name: Set up Docker Buildx
        run: |
          
          proyect=("myproyecto1" "myproyecto2")
          for proy in "${proyect[@]}"; do
            echo "Docker images built $proy"
            pathfile=./$proy/Dockerfile
            tag=$proy:${{env.TAGS}}
            docker buildx build --file $pathfile --tag $tag .
          done

          docker images


      # - name: Build Docker image 2
      #   run: |
      #     echo "Docker images built successfully"
      #     docker buildx build --file ./myproyecto1/Dockerfile --tag dso-lambda-ecr-serverless:${{env.TAGS}}
      #     echo "Docker images tags successfully"
      #     docker build -t dso-lambda-ecr-serverless:${{env.TAGS}} -f ./myproyecto2/Dockerfile .
      #     echo "Docker images list"
      #     docker images
      
      # - run: docker images
      #   name: List Docker images
