name: CI
run-name: "CI/CD - Build & Push to ECR 1.0.${{ github.run_number }}"

on:
  push:
    branches:
       - main
#       - develop
#   pull_request:
#     branches:
#       - main
  workflow_dispatch:
    inputs:
      proyectos:
        description: 'Selecciona el proyecto a desplegar'
        required: true
        default: 'myproyecto1'
        type: choice
        options:
          - myproyecto1
          - myproyecto2
          - myproyecto3

env:
    TAGS: 1.0.${{ github.run_number }}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # Required for OIDC authentication

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: proyecto
        run: |
          echo "Proyecto seleccionado: ${{ inputs.proyectos || 'myproyecto1' }}"
        
      - name: Carga de variables y Build
        run: |
          set -e

          echo "---- Proyectos disponibles en config.yml ----"
          yq e '.proyectos[].proyectoid' ./config.yml
          echo "---------------------------------------------"

          # Iterar cada proyectoid y ejecutar docker buildx build
          while IFS= read -r proy; do
            echo "Docker images built: $proy"
            pathfile=./$proy/Dockerfile
            tag=$proy:${{ env.TAGS }}
            docker buildx build --file $pathfile --tag $tag .
          done < <(yq e '.proyectos[].proyectoid' ./config.yml)

          docker images



      # - name: Build Docker image 2
      #   run: |
      #     echo "Docker images built successfully"
      #     docker buildx build --file ./myproyecto1/Dockerfile --tag dso-lambda-ecr-serverless:${{env.TAGS}}
      #     echo "Docker images tags successfully"
      #     docker build -t dso-lambda-ecr-serverless:${{env.TAGS}} -f ./myproyecto2/Dockerfile .
      #     echo "Docker images list"
      #     docker images
      
      # - run: docker images
      #   name: List Docker images
